version: "3.8"

services:
  redis:
    image: 'redis:latest'
    container_name: redis-training
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - default-network

  n8n:
    image: n8nio/n8n:next
    container_name: n8n-training
    ports:
      - "9090:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=https://oarfish-relaxing-whippet.ngrok-free.app
      - WEBHOOK_URL=https://oarfish-relaxing-whippet.ngrok-free.app
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    networks:
      - default-network
    volumes:
      - D:\workspace\n8n\n8n_data:/home/node/.n8n

networks:
  default-network:
    driver: bridge