server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final-exercise
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  duration: 1 #hour
  refresh-duration: 3 #hour
