server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final-exercise
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html

open:
  api:
    title: API Documents
    version: v1.0.0
    description: APIs docs for Team Solutions Training course
    serverUrl: ${API_SERVER_URL:http://localhost:8081}
    serverDescription: local

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  duration: 1 #hour
  refresh-duration: 3 #hour

brevo:
  api-key: ${API_KEY_BREVO}
  template-forget-password: 3
  template-verify-email: 5

clients:
  brevo-client:
    name: brevo-client
    url: https://api.brevo.com/v3/smtp/email
  n8n-client:
    name: n8n-client
    url: https://oarfish-relaxing-whippet.ngrok-free.app/webhook/register
