server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final-exercise
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  duration: 1 #hour
  refresh-duration: 3 #hour

brevo:
  api-key: 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
  template-id: 3
